models
mvoevodskiy/mvl-tasks pull request #1
Opened 2020-01-24 19:05 UTC by Eduard20

2020-01-24 22:37 UTC, mvoevodskiy requested changes
Что будет результатом, если вызвать без указания вложенного пути?

const mvlTasks = require(‘mvl-tasks’);

—————

  "main": "src/mvlblankproject.js",

2020-01-24 22:37 UTC, mvoevodskiy commented on package.json
> -    "mvloader": "git+https://github.com/mvoevodskiy/mvloader.git",
Почему исключён из зависимостей? Основной экспортируемый класс зависит от наличия mvloader.

2020-01-27 15:45 UTC, Eduard20 commented
во что именно переименовать mvlblanksemis.js?

2020-01-27 15:47 UTC, Eduard20 commented
к чему вопрос по этому?
const mvlTasks = require(‘mvl-tasks’);

2020-01-28 01:00 UTC, mvoevodskiy commented
> во что именно переименовать mvlblanksemis.js?

mvltaskssemis

2020-01-28 01:02 UTC, mvoevodskiy commented
> к чему вопрос по этому?
> const mvlTasks = require(‘mvl-tasks’);

В packages.json указывается основной файл, который вызывается при загрузке пакета. Сейчас там указан уже несуществующий файл, что вызовет ошибку.

2020-01-28 18:21 UTC, mvoevodskiy approved these changes

2020-01-28 18:21 UTC, merged